branches: {only: [master, develop]}
dist: xenial
sudo: false
language: python
python:
  - 3.6 
cache: pip

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6

matrix:
  include:
    - name: Unit tests
      env: DEBUG=1 DATABASE_URL=postgres:///django_ilmoitin
      services: [postgresql]
      install: pip install -r requirements-test.txt
      before_script:
        - createdb django_ilmoitin
        - pip install -e .
      script: pytest -ra -vv --doctest-modules --cov django_ilmoitin
      after_success: pip install codecov && codecov

    - name: Coding style
      install: pip install -r requirements-test.txt
      script:
        - black --check .
        - flake8
        - isort -c
