[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "django_ilmoitin"
version = "0.7.1"
description = "Django app for sending notifications."
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    {name = "City of Helsinki", email = "dev@hel.fi"},
]
requires-python = ">=3.10"
classifiers = [
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 4.2",
    "Framework :: Django :: 5.1",
    "Framework :: Django :: 5.2",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]
dependencies = [
    "Django>=4.2",
    "django-parler>=2.0",
    "django-anymail",
    "django-mailer",
    "jinja2",
]

[project.optional-dependencies]
graphql_api = [
    "graphene>=2.0",
    "graphene-django",
    "graphql-core<3,>=2.1",
    "graphql-relay<3,>=2",
]

[project.urls]
Homepage = "https://github.com/City-of-Helsinki/django-ilmoitin"

[tool.hatch.build.targets.wheel]
packages = ["django_ilmoitin"]

[tool.coverage.run]
source = ["django_ilmoitin"]
omit = ["**/migrations/*", "**/tests/*"]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
DJANGO_SETTINGS_MODULE = "tests.settings"
pythonpath = "."
norecursedirs = [
    "bower_components",
    "node_modules",
    ".git",
    ".idea",
    "test_app"
]
doctest_optionflags = [
    "NORMALIZE_WHITESPACE",
    "IGNORE_EXCEPTION_DETAIL",
    "ALLOW_UNICODE"
]

[tool.ruff]
target-version = "py310"

[tool.ruff.lint]
select = [
    # Pyflakes
    "F",
    # pycodestyle
    "E",
    "W",
    # isort
    "I",
    # pep8-naming
    "N",
    # flake8-bugbear without opinionated rules
    "B0",
    # flake8-pie
    "PIE",
    # flake8-print
    "T20",
]
