# Generated by Django 3.2.6 on 2021-08-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ilmoitin', '0004_update_translation_master_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
