# Generated by Django 4.2.16 on 2024-10-17 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_ilmoitin", "0006_alter_notificationtemplatetranslation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationtemplate",
            name="admins_to_notify",
            field=models.ManyToManyField(
                blank=True,
                help_text="Choose admin users you want to be notified when this event happens.",
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Admins to notify",
            ),
        ),
    ]
